### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by rajivr754** [tagDiv/ionMag#2]
Errors happened during tdcIframeData.init() -> bindViewsModelsWrappers()!
i am facing this error when i am adding anything through tagdiv and noting shows on the page after saving

**Comment by opradu** [comment]
Hi,
can you please give us your site's url? Are you using the latest version of the theme and td-composer plugin?

**Comment by panosnet** [comment]
Hi, I had the same exact issue. This is caused because of mixed content (http/https). The quick fix is to click on the icon next to the url box of your browser. The icon is for insecure content. If you click on it you can select allow insecure content to run. The browser will reload and you will be good to go!

**Comment by adamesss** [comment]
I have this same error installing the editor in Newsmag theme (Latest Edition) :(

**Comment by cristealucian** [comment]
Hi,
Unfortunately the Newsmag theme current available version and td-composer plugin are not yet compatible. Newsmag version 3 will be compatible with the td composer plugin. 
The latest version of the ionMag theme (Version: 1.5.1 - Release date: 10.05.2017) should fix these matters so please update you theme and let us know if you still have issues and please also provide a link and contact our theme support forum: https://www.wpion.com/members/forum/ionmag/
