### ISSUE TITLE
No p tags on pages

### ISSUE THREAD

**Issue by shubhra14** [tagDiv/ionMag#6]
Hi,

Paragraph tags are not being added on the pages. Example page: https://demo.tagdiv.com/ionmag/contact/

**Comment by cristealucian** [comment]
@shubhra14 

Thank you! This will be fixed in the next version of the theme and tagdiv composer plugin which will be available soon; please update your theme once it's available and let us know if you still have issues and please also provide a link and contact our theme support forum here: https://www.wpion.com/members/forum/ionmag/
